AF\Domain\Algorithm\Selection\TextKey\ContextValueSelectionAlgo:
  type: entity
  repositoryClass: Core_Model_Repository_Ordered
  table: Algo_Selection_TextKey_ContextValue

  fields:
    name:
      type: string
      nullable: false
    defaultValue:
      type: string
      nullable: false
