# Activation des ACL
enable.acl: true

# DÃ©finit dans le bootstrap:
# application.name:
# email.contact.address:
# email.noreply.name:
# email.noreply.address:

# Notification des taches de fond
Core\Work\Notification\TaskNotifier:
  class: Core\Work\Notification\EmailTaskNotifier
Core\Work\Notification\EmailTaskNotifier:
  constructor:
    userService: User_Service_User
    contactAddress: email.contact.address
    applicationName: email.noreply.name
